version: "3.7"

services:
  postgres:
    build:
      context: ./docker/postgresql
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: "automoderator"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "automoderator"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U automoderator"]
      interval: 10s
      timeout: 5s

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    environment:
      DB_URL: "postgres://automoderator:admin@postgres:5432/automoderator?sslmode=disable"
    restart: unless-stopped

  auth:
    build:
      context: ./
      dockerfile: ./docker/auth/Dockerfile
    environment:
      DB_URL: "postgres://automoderator:admin@postgres:5432/automoderator?sslmode=disable"
      DISCORD_SCOPES: "identify,email"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 60s
      timeout: 5s

  gateway:
    image: cordislib/gateway:latest
    environment:
      CORDIS_AMQP_HOST: "amqp://rabbitmq:5672"
      CORDIS_WS_INTENTS: "guildMessages"
    restart: unless-stopped

volumes:
  elis-data:
    name: "automoderator-elis-data"
  postgres-data:
    name: "automoderator-postgres-data"
