version: "3.7"

services:
  automod:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "https://api.automoderator.me"
    command: "sh -c \"node services/automod/dist/index.js | ./services/automod/node_modules/.bin/pino-elasticsearch\""

  api:
    environment:
      NODE_ENV: "prod"
    command: "sh -c \"node services/api/dist/index.js | ./services/api/node_modules/.bin/pino-elasticsearch\""

  auth:
    environment:
      ROOT_DOMAIN: "https://automoderator.me"
      AUTH_DOMAIN: "https://auth.automoderator.me"
      API_DOMAIN: "https://api.automoderator.me"
      NODE_ENV: "prod"
    command: "sh -c \"node services/auth/dist/index.js | ./services/auth/node_modules/.bin/pino-elasticsearch\""

  commands:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "https://api.automoderator.me"
    command: "sh -c \"node services/commands/dist/index.js | ./services/commands/node_modules/.bin/pino-elasticsearch\""

  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - elis-data:/usr/share/elasticsearch/data
    environment:
      "discovery.type": "single-node"
      "bootstrap.memory_lock": "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.12.1
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
