version: "3.7"

services:
  api:
    environment:
      NODE_ENV: "prod"
    command: "sh -c \"node services/api/dist/index.js | ./services/api/node_modules/.bin/pino-elasticsearch --index api-v1 --node http://elasticsearch:9200\""

  auth:
    environment:
      ROOT_DOMAIN: "https://automoderator.app"
      AUTH_DOMAIN: "https://auth.automoderator.app"
      NODE_ENV: "prod"
    command: "sh -c \"node services/auth/dist/index.js | ./services/auth/node_modules/.bin/pino-elasticsearch --index auth-v1 --node http://elasticsearch:9200\""

  automod:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "http://api:3001"
    command: "sh -c \"node services/automod/dist/index.js | ./services/automod/node_modules/.bin/pino-elasticsearch --index automod-v1 --node http://elasticsearch:9200\""

  cron-runner:
    environment:
      NODE_ENV: "prod"
    command: "sh -c \"node services/cron-runner/dist/index.js | ./services/cron-runner/node_modules/.bin/pino-elasticsearch --index cron-runner-v1 --node http://elasticsearch:9200\""

  interactions:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "http://api:3001"
    command: "sh -c \"node services/interactions/dist/index.js | ./services/interactions/node_modules/.bin/pino-elasticsearch --index interactions-v1 --node http://elasticsearch:9200\""

  logging:
    environment:
      NODE_ENV: "prod"
    command: "sh -c \"node services/logging/dist/index.js | ./services/logging/node_modules/.bin/pino-elasticsearch --index logging-v1 --node http://elasticsearch:9200\""

  mod-observer:
    environment:
      NODE_ENV: "prod"
    command: "sh -c \"node services/mod-observer/dist/index.js | ./services/mod-observer/node_modules/.bin/pino-elasticsearch --index mod-observer-v1 --node http://elasticsearch:9200\""

  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - elis-data:/usr/share/elasticsearch/data
    environment:
      "discovery.type": "single-node"
      "bootstrap.memory_lock": "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.12.1
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
