version: "3.7"

services:
  api:
    environment:
      NODE_ENV: "prod"
      ELASTIC_URL: "http://elasticsearch:9200"

  auth:
    environment:
      ROOT_DOMAIN: "https://automoderator.app"
      AUTH_DOMAIN: "https://api.automoderator.app"
      NODE_ENV: "prod"
      ELASTIC_URL: "http://elasticsearch:9200"

  automod:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "http://api:3001"
      ELASTIC_URL: "http://elasticsearch:9200"

  cron-runner:
    environment:
      NODE_ENV: "prod"
      ELASTIC_URL: "http://elasticsearch:9200"

  interactions:
    environment:
      NODE_ENV: "prod"
      API_DOMAIN: "http://api:3001"
      ELASTIC_URL: "http://elasticsearch:9200"

  logging:
    environment:
      NODE_ENV: "prod"
      ELASTIC_URL: "http://elasticsearch:9200"

  mod-observer:
    environment:
      NODE_ENV: "prod"
      ELASTIC_URL: "http://elasticsearch:9200"

  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - api
      - auth
      - interactions
      - elasticsearch
      - kibana
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

  elasticsearch:
    image: elasticsearch:7.12.1
    volumes:
      - elis-data:/usr/share/elasticsearch/data
    environment:
      "discovery.type": "single-node"
      "bootstrap.memory_lock": "true"
      "xpack.security.enabled": "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.12.1
    restart: unless-stopped
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: "kibana_system"
