version: "3.7"

services:
  automod:
    environment:
      DISCORD_TOKEN: "awooga"
      INTERNAL_API_KEY: "asdf"

  auth:
    environment:
      DISCORD_CLIENT_ID: "123"
      DISCORD_CLIENT_SECRET: "abc"
      DISCORD_TOKEN: "def"
      ENCRYPTION_KEY: "32 random bytes of base64 here"
