version: '3.7'

services:
  api:
    image: chatsift/automoderator_api
    build:
      context: ../
      dockerfile: ./docker/api/Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_SCOPES: 'identify,email,guilds'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    depends_on:
      - base

  automod:
    image: chatsift/automoderator_automod
    build:
      context: ../
      dockerfile: ./docker/automod/Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    depends_on:
      - base

  base:
    image: chatsift/automoderator_base
    build:
      context: ../
      dockerfile: ./docker/base/Dockerfile

  discord-proxy:
    image: chatsift/automoderator_discord-proxy
    build:
      context: ../
      dockerfile: ./docker/discord-proxy/Dockerfile
    restart: unless-stopped
    depends_on:
      - base

  gateway:
    image: chatsift/automoderator_gateway
    build:
      context: ../
      dockerfile: ./docker/gateway/Dockerfile
    environment:
      AMQP_URL: 'amqp://rabbitmq:5672'
      REDIS_URL: 'redis://redis:6379/0'
    restart: unless-stopped
    depends_on:
      - base

  interactions:
    image: chatsift/automoderator_interactions
    build:
      context: ../
      dockerfile: ./docker/interactions/Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    depends_on:
      - base

  logging:
    image: chatsift/automoderator_logging
    build:
      context: ../
      dockerfile: ./docker/logging/Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    depends_on:
      - base

  mod-observer:
    image: chatsift/automoderator_mod-observer
    build:
      context: ../
      dockerfile: ./docker/mod-observer/Dockerfile
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    depends_on:
      - base
