version: '3.7'

services:
  service:
    image: chatsift/automoderator_service
    build:
      context: ../
      dockerfile: ./docker/service/Dockerfile

  automod:
    image: chatsift/automoderator_service
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/automod/dist/index.js']

  discord-proxy:
    image: chatsift/automoderator_service
    volumes:
      - ../logs:/usr/service/logs
    restart: unless-stopped
    expose:
      - 3003
    command: ['node', '--enable-source-maps', 'services/discord-proxy/dist/index.js']

  gateway:
    image: chatsift/automoderator_service
    environment:
      AMQP_URL: 'amqp://rabbitmq:5672'
      REDIS_URL: 'redis://redis:6379/0'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/gateway/dist/index.js']

  interactions:
    image: chatsift/automoderator_service
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    expose:
      - 3002
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/interactions/dist/index.js']

  logging:
    image: chatsift/automoderator_service
    environment:
      DB_URL: '${DB_URL}'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/logging/dist/index.js']

  mod-observer:
    image: chatsift/automoderator_service
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/mod-observer/dist/index.js']

  scheduler:
    image: chatsift/automoderator_service
    environment:
      DB_URL: '${DB_URL}'
      REDIS_URL: 'redis://redis:6379/0'
      AMQP_URL: 'amqp://rabbitmq:5672'
      DISCORD_PROXY_URL: 'http://discord-proxy:3003'
    restart: unless-stopped
    volumes:
      - ../logs:/usr/service/logs
    command: ['node', '--enable-source-maps', 'services/scheduler/dist/index.js']
