version: '3.7'

services:
  automod:
    environment:
      DISCORD_CLIENT_ID: '123'
      DISCORD_TOKEN: 'awooga'
      DEV_IDS: '123,456'
      NSFW_PREDICT_API_KEY: 'something'

  discord-proxy:
    environment:
      DISCORD_TOKEN: 'awooga'

  gateway:
    environment:
      DISCORD_TOKEN: 'awooga'

  interactions:
    environment:
      DISCORD_CLIENT_ID: '123'
      INTERACTIONS_TEST_GUILDS: '456,789'
      DISCORD_PUB_KEY: 'owo'
      DISCORD_TOKEN: 'awooga'
      DEV_IDS: '123,456'

  logging:
    environment:
      DISCORD_TOKEN: 'awooga'

  mod-observer:
    environment:
      DISCORD_CLIENT_ID: '123'
      DISCORD_TOKEN: 'awooga'

  scheduler:
    environment:
      DISCORD_CLIENT_ID: '123'
      DISCORD_TOKEN: 'awooga'

  caddy:
    environment:
      CF_API_TOKEN: 'pls fill'
      BASIC_AUTH_KEY: 'may also need to fill'

  ghost:
    environment:
      mail__options__auth__user: 'username here'
      mail__options__auth__pass: 'pass here'
