version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    expose:
      - '5672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 60s
      timeout: 5s

  postgres:
    build:
      context: ../docker/postgresql
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_USER: 'automoderator'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'automoderator'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U automoderator']
      interval: 10s
      timeout: 5s

  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping']
      interval: 10s
      timeout: 5s

volumes:
  elis-data:
    name: 'automoderator-elis-data'
  redis-data:
    name: 'redis-data'
  postgres-data:
    name: 'automoderator-postgres-data'
  ghost-data:
    name: 'automoderator-ghost-data'
