version: '3.7'

services:
  automod:
    environment:
      NODE_ENV: 'dev'

  discord-proxy:
    environment:
      NODE_ENV: 'dev'

  gateway:
    environment:
      NODE_ENV: 'dev'

  interactions:
    environment:
      NODE_ENV: 'dev'
    ports:
      - '127.0.0.1:3002:3002'
    command: ['node', '--enable-source-maps', 'services/interactions/dist/index.js']

  logging:
    environment:
      NODE_ENV: 'dev'

  mod-observer:
    environment:
      NODE_ENV: 'dev'

  scheduler:
    environment:
      NODE_ENV: 'dev'

  postgres:
    ports:
      - '127.0.0.1:5433:5432'
