version: '3.7'

services:
  api:
    environment:
      NODE_ENV: 'prod'
      ROOT_DOMAIN: 'https://automoderator.app'
      API_DOMAIN: 'https://api.automoderator.app'
      GHOST_DOMAIN: 'https://blog.automoderator.app'
      CORS: 'https://dash.automoderator.app'

  automod:
    environment:
      NODE_ENV: 'prod'
      API_DOMAIN: 'http://api:3001'

  discord-proxy:
    environment:
      NODE_ENV: 'prod'

  gateway:
    environment:
      NODE_ENV: 'prod'

  interactions:
    environment:
      NODE_ENV: 'prod'
      API_DOMAIN: 'http://api:3001'

  logging:
    environment:
      NODE_ENV: 'prod'

  mod-observer:
    environment:
      NODE_ENV: 'prod'
      API_DOMAIN: 'http://api:3001'

  scheduler:
    environment:
      NODE_ENV: 'prod'
      API_DOMAIN: 'http://api:3001'

  caddy:
    build:
      context: ../
      dockerfile: ./docker/caddy/Dockerfile
    depends_on:
      - api
      - interactions
    ports:
      - '80:80'
      - '443:443'

  ghost:
    image: ghost:4-alpine
    restart: unless-stopped
    expose:
      - 2368
    environment:
      NODE_ENV: 'production'
      url: 'https://blog.automoderator.app'
      database__client: 'sqlite3'
      mail__transport: 'SMTP'
      mail__options__service: 'Mailgun'
    volumes:
      - ghost-data:/var/lib/ghost/content

  postgres:
    ports:
      - '127.0.0.1:5432:5432'
