name: Quality Check

on: [push, pull_request]

jobs:
  checks:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install deps
        run: yarn --immutable

      - name: Make sure prisma schema is up to date
        run: yarn prisma generate

      - name: Build the code
        run: yarn run build

      - name: Run ESLint
        run: yarn run lint

      - name: Run Jest Tests
        run: yarn run test:ci
